(function(a,u,p){function e(a,b){a.super_=b;g.prototype=b.prototype;a.prototype=new g;a.prototype.constructor=a}function g(){}function w(a,b){for(var q in b)b.hasOwnProperty(q)&&(a[q]=b[q]);return a}function n(a,b){return(b=b||p)&&b.getElementById&&b.getElementById(a)}function z(a,b){var q=b?a.substr?n(a):a:p;return q?q.getElementsByTagName(b||a):[]}function B(a,b){return~(" "+a.className+" ").indexOf(" "+b+" ")}function x(a,b){B(a,b)&&(a.className=(" "+a.className+" ").replace(" "+b+" "," ").slice(1,
-1),x(a,b))}function v(a){var q=a.offsetTop,c=a.offsetLeft,d,e=b.curCSS,f="static"!=e(a,"position");q||(q=(parseFloat(e(a,"marginTop"))||0)+(f?parseFloat(e(a,"top"))||0:0));c||(c=(parseFloat(e(a,"marginLeft"))||0)+(f?parseFloat(e(a,"left"))||0:0));f&&a.getBoundingClientRect&&(d=b.offset(a,!0));!q&&d&&(q=d.top);!c&&d&&(c=d.left);return{top:q,left:c}}function H(a){var b={relativeX:a[y[0]],relativeY:a[y[1]]};if(null==a.pageX&&null!=a.clientX){var q=p.documentElement,c=p.body;b.pageX=a.clientX+(q&&q.scrollLeft||
c.scrollLeft||0);b.pageY=a.clientY+(q&&q.scrollTop||c.scrollTop||0)}else b.pageX=a.pageX,b.pageY=a.pageY;return b}function P(a,c){if(!(a=a.parentNode))return!1;var q=a.ownerDocument,d=q.body,e=b.curCSS,X;c&&(c+=1);if(u.$sf)return!0;if(b.isIE&&(8>q.documentMode||"BackCompat"==q.compatMode))return!1;for(;a&&a!=d;){if("hidden"==e(a,"overflow"))return!1;if("fixed"==e(a,"position"))break;else if(c&&(X=parseInt(e(a,"z-index"),10))&&X<c)return!1;a=a.parentNode}return!0}function l(){for(var a=0,b=[];a<W.length;a++)"complete"!=
W[a].document.readyState&&b.push(W[a]);if(!(W=b).length||3E4<(new Date).getTime()-F){E=clearInterval(E);for(a=0;a<L.length;a++)L[a]();L=[];W=[]}}function f(a,b){var q=Math.max(a.x,b.x),c=Math.max(a.y,b.y),d=Math.min(a.x+a.width,b.x+b.width)-q;a=Math.min(a.y+a.height,b.y+b.height)-c;return 0<d&&0<a?{x:q,y:c,width:d,height:a}:{x:0,y:0,width:0,height:0}}function N(a,c,d,e){var q=function(a){e&&e.apply(a,arguments)},f=z(d,"head");f=f&&f[0];if(!f)try{throw Error("Can't find head tag.");}catch(ca){q(ca)}var X=
c.src||c.href,g=X.replace(/[^\da-z_-]/gi,"_"),ba=d.adformId||b.gid("doc_"),k=ba+"|"+g,h=Z[k];g=b.byTag(d,a);var V=0,l=g.length;d.adformId=d.adformId||ba;if(h)h.loaded?q():h.callbacks.push(q);else{for(;V<l;++V)if(g[V].src==X||g[V].href==X){q();return}Z[k]=h={doc:d,src:X,callbacks:[q]};var m=d.createElement(a);w(m,c);if(e){var n=function(a){m.onload=m.onreadystatechange=m.onerror=null;a?Z[k]=null:h.loaded=1;var b=h.callbacks;V=0;for(l=b.length;V<l;++V)b[V](a)};m.onload=function(){n()};m.onreadystatechange=
function(){"complete"==m.readyState&&n()};m.onerror=function(){try{throw Error("Failed to load script: "+X);}catch(ca){n(ca)}}}setTimeout(function(){f.insertBefore(m,f.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var d=a.RMB,b=d.lib||(d.lib={});a.lib||(a.lib=b);b.inherit=e;b.define=function(a,b,c){c&&e(a,b);c(a,a.prototype)};b.gid=function(a){var b=+new Date;return(a||"")+(b+b*~~(1E4*Math.random())).toString(36)};
b.byId=n;b.byTag=z;b.bind=function(a,b){return function(){return b.apply(a,arguments)}};b.extend=w;b.isMouseLeave=function(a,b){if(!a||"mouseout"!=a.type)return!0;a=a.relatedTarget||a.toElement;for(var c,q=b.length;a;){for(c=0;c<q;c++)if(b[c]==a)return!1;a=a.parentNode}return!0};b.singleCall=function(a){function b(){e=!1;var a=q,b=c,f=d;c=q=d=null;a&&a.apply(b,f)}var c,q,d,e;return function(f,g){c=f;q=g;d=r.call(arguments,2);g&&!e?e=setTimeout(b,a):!g&&e&&(clearTimeout(e),e=!1)}};b.onload=function(a,
b){try{do{if(a[O])break;a[O]=!0;"complete"!=a.document.readyState&&(W.push(a),E||(F=(new Date).getTime(),E=setInterval(l,200)))}while(a!=a.parent&&(a=a.parent))}catch(ba){}E?L.push(b):setTimeout(b,0)};b.overlap=f;b.overlapElem=function(a,c){var d=b.offset(a),q=b.offset(c);return f({x:d.left,y:d.top,width:a.offsetWidth,height:a.offsetHeight},{x:q.left,y:q.top,width:c.offsetWidth,height:c.offsetHeight})};b.hasClass=B;b.addClass=function(a,b){B(a,b)||(a.className+=" "+b)};b.removeClass=x;b.loadScript=
function(a,b,c){N("script",{src:b,type:"text/javascript"},a,c)};b.loadCSS=function(a,b){N("link",{href:b,type:"text/css",rel:"stylesheet"},a)};b.navigator=u.navigator;b.isTMX=function(a){try{var b=a.document,c=b&&b.body;return c&&B(c,"tmx")}catch(V){}return!1};b.isolate=function(a,b){var c=a.__adform_isolate;if(!c){var d=a.document;c=z(d,"head")[0];d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';c.insertBefore(d,
c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(b):(new Function("window","("+b+")(window)"))(a)};var r=Array.prototype.slice;b.addEvent=function(a,b,c){return a[C]?a[C](b,c,!1):a[h]?a[h]("on"+b,c):!1};b.removeEvent=function(a,b,c){return a[A]?a[A](b,c,!1):a[k]?a[k]("on"+b,c):!1};var C="addEventListener",A="removeEventListener",h="attachEvent",k="detachEvent",t=/([A-Z])/g,m=/^-?\d+(?:px)?$/i,T=/^-?\d/;a=p.defaultView;b.curCSS=a&&a.getComputedStyle?function(a,b){var c=a.ownerDocument.defaultView;
if(c&&(c=c.getComputedStyle(a,null)))return c.getPropertyValue(b.replace(t,"-$1").toLowerCase())||a.style[b]}:p.documentElement.currentStyle&&function(a,b){var c,d,e=a.currentStyle&&a.currentStyle[b];if(!m.test(e)&&T.test(e)){var q=(d=a.style).left;if(c=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;d.left="fontSize"===b?"1em":e||0;e=d.pixelLeft+"px";d.left=q;c&&(a.runtimeStyle.left=c)}return""===e?"auto":e};var R=function(){function a(){return a}var b=p.body,c=p.createElement("div");
var d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
b.insertBefore(c=c.firstChild,b.firstChild);d=c.childNodes;a.dnab=5!==d[0].firstChild.offsetTop;a.sfp=20===d[1].firstChild.offsetTop;a.sbfonv=-5===d[2].firstChild.offsetTop;a.dabftac=5===z(c,"td").offsetTop;b.removeChild(c);b=c=d=null;return R=a},S=/^t(?:able|d|h)$/i;b.offsetFromWindow=function(a){var c=a&&a.ownerDocument;if(!c)return null;var d=c.documentElement;if("getBoundingClientRect"in d){try{var e=a.getBoundingClientRect();var f=d.getBoundingClientRect()}catch(fa){}if(!e)return{top:0,left:0};
if(0<f.left||0<f.top)e.top-=f.top,e.left-=f.left;return{top:e.top,left:e.left}}e=c.defaultView||c.parentWindow;f=c.body;if(a===c.body)return v(a);a=b.offset(a);c=e&&e.pageYOffset||d.scrollTop||f.scrollTop;d=e&&e.pageXOffset||d.scrollLeft||f.scrollLeft;a.top-=c;a.left-=d;return a};b.offset="getBoundingClientRect"in p.documentElement?function(a,b){var c=a&&a.ownerDocument;if(!c)return null;if(!b&&a===c.body)return v(a);try{var d=a.getBoundingClientRect()}catch(ea){}if(!d)return{top:0,left:0};a=c.body;
c=c.documentElement;return{top:d.top+(c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0),left:d.left+(c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0)}}:function(a){var b=a&&a.ownerDocument;if(!b)return null;if(a===b.body)return v(a);var c=a.offsetParent,d=b.documentElement,e=b.body;var f=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var g=a.offsetTop,h=a.offsetLeft,k=R();(a=a.parentNode)&&a!==e&&a!==d&&(!k.sfp||"fixed"!==f.position);)f=b?b.getComputedStyle(a,null):
a.currentStyle,g-=a.scrollTop,h-=a.scrollLeft,a===c&&(g+=a.offsetTop,h+=a.offsetLeft,!k.dnab||k.dabftac&&S.test(a.nodeName)||(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0),c=a.offsetParent),k.sbfonv&&"visible"!==f.overflow&&(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0);if("relative"===f.position||"static"===f.position)g+=e.offsetTop,h+=e.offsetLeft;k.sfp&&"fixed"===f.position&&(g+=Math.max(d.scrollTop,e.scrollTop),h+=Math.max(d.scrollLeft,e.scrollLeft));
return{top:g,left:h}};b.client=function(a){a=a.ownerDocument||a;var b=a.defaultView||a.parentWindow;var c=a.documentElement;var d=a.body;if(b.innerWidth){a=b.innerWidth;var e=b.innerHeight}else c?(a=c.clientWidth,e=c.clientHeight,a&&d.clientHeight==d.offsetHeight||(a=Math.min(a||123456789,d.clientWidth||123456789),e=Math.min(e||123456789,d.clientHeight||123456789))):(a=d.clientWidth,e=d.clientHeight);return{left:b&&b.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,top:b&&b.pageYOffset||c&&c.scrollTop||
d&&d.scrollTop||0,width:a,height:e}};b.isArray=Array.isArray||function(a){return"[object Array]"==Object.prototype.toString.call(a)};var y=[["offsetX","offsetY"],["layerX","layerY"]];b.getMousePos=function(a){for(var c;c=y.shift();)if("undefined"!=typeof a[c[0]]){y=c;break}c||(y=["x","y"]);b.getMousePos=H;return H(a)};var M=p.createElement("div");b.html=function(a,b){b=!b&&M||b.createElement("div");b.innerHTML=a;return b.firstChild&&b.removeChild(b.firstChild)};a=b.navigator;var D=a.vendor;a=a.userAgent;
var U=/Apple Computer/i.test(D);d=/Google/i.test(D);var Q=b.isIPad=/iPad/i.test(a),K=b.isIPhone=/iPhone/i.test(a),G=b.isIOS=Q||K,I=b.isTouch="ontouchstart"in p.documentElement||"ontouchstart"in u;Q=b.isOrientation="orientation"in u;K=b.isAndroid=!G&&/Android/i.test(a);b.isAndroidApp=K&&!/^(?:Opera|Mozilla)/i.test(a);var J;b.isIOSF=G&&(J=/\sos\s(\d+)_\d+/i.exec(a))&&(J=4<J[1]>>0);var c=b.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||I;J=b.isIE=/msie|Trident/i.test(a);I=b.isFF=/Firefox[\/.]+[^\s]/i.test(a);
b.isMACOS=/Mac OS X/i.test(a);(b.isWinPhone=J&&c&&/Phone/gi.test(a))&&(c=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(a))&&c[2]&&(b.winPhoneVer=parseFloat(c[2]));c=b.isOpera=/Opera/i.test(a);var Y=b.isOperaMobile=/Opera\s(?!Mini)/i.test(a),aa=b.isOperaMini=/Opera\sMini/i.test(a);D=b.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(D);G=b.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(G?U:d);U=b.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&U;d=b.isInternet=K&&!G&&Q&&/Safari\/[\.\d]+$/i.test(a)&&
d;b.isEdge=/Edge\/[\.\d]+$/i.test(a);b.isAfmaSDK=/afma-sdk/i.test(a);var da=J?"msie":I?"firefox":Y?"operaMobile":aa?"operaMini":c?"opera":D?"operaWebKit":G?"chrome":U?"safari":d?"internet":!1;b.browser=function(){return da};b.isIE&&("Microsoft Internet Explorer"==b.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))&&(b.ieVersion=parseFloat(RegExp.$1));b.testPlace=b.isIE&&8>b.ieVersion?function(){return!1}:P;b.isSafari&&(a=/Version.([\d.]+)/.exec(a),b.safariVersion=parseFloat(a&&
a[1]));var W=[],L=[],O="__adform_onload",E,F,Z={}})(Adform=window.Adform||{},window,document);
(function(a){function u(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=u;var p=Array.prototype.slice;a=u.prototype;a.emit=function(a){var e=this._events,w=!1,n=arguments;if(e&&(e=e[a]))if("function"==typeof e){switch(n.length){case 1:e.call(this);break;case 2:e.call(this,n[1]);break;case 3:e.call(this,n[1],n[2]);break;case 4:e.call(this,n[1],n[2],n[3]);break;default:e.apply(this,p.call(n,1))}w=!0}else if(e.length){n=p.call(n,1);e=e.slice();w=0;for(var u=e.length;w<u;w++)e[w].apply(this,n);w=!0}else delete this._events[a];
return w};a.on=function(a,g){this._events||(this._events={});this.emit("newListener",a,g);var e=this._events;e[a]?"function"==typeof e[a]?e[a]=[e[a],g]:e[a].push(g):e[a]=g;return this};a.once=function(a,g){var e=g._once;e?e._times++:(e=g._once=function(){this.off(a,e);1>--e._times&&delete g._once;return g.apply(this,arguments)},e._times=1);return this.on(a,e)};a.off=function(a,g){if(!this._events||!this._events[a])return this;var e=this._events,n=e[a];if(n==g)return delete e[a],this;g&&g._once&&this.off(g._once);
if("function"==typeof n)return this;if(2>n.length&&n[0]==g)return delete e[a],this;for(var p=0,u=n.length,x=[];p<u;p++)n[p]!=g&&x.push(n[p]);x.length!=u&&(x.length?e[a]=x:delete e[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var e=this._events;e[a]?"function"==typeof e[a]&&(e[a]=[e[a]]):e[a]=[];return e[a]}})(Adform=window.Adform||{});
/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
(function(a,u,p){function e(a){return parseInt(a,10)?a:0}function g(){}function w(a,g,e){function l(){d=!1;var b=v;v=[];e(function(a){for(var d=0;d<b.length;d++)if(a)b[d][1](a);else f(b[d][0],b[d][1])})}function f(b,r){var f=!1;g(b,function(){f=!0;r.apply(this,arguments)});f||(v.push([b,r]),d||(d=setTimeout(l,a)))}var v=[],d=!1;return f}function n(a,g,e){var l=a["@id"]||0;var f=a["@pdata"]||"";var v={$id:l,$name:a["@name"]||"default",$link:e.replace(/adfibeg=\d+/,f?"pdata="+f:"adfibeg="+l),$pdata:f};
if(a.TextVars)for(e=0,l=a.TextVars.TextVar,f=l.length,x.isArray(l)||(l=[l],f=1);e<f;e++){var d=l[e];var b=d["@name"];d=d["@value"];v[b]=d;"product_deeplink"==b&&(v.$link+=";cpdir="+encodeURIComponent(d))}if(a.Graphics)for(e=0,l=a.Graphics.Graphic,f=l.length,x.isArray(l)||(l=[l],f=1);e<f;e++)d=l[e],v[d["@name"]]=g+d["@value"]+"?assetID="+d["@assetID"]+"&av="+d["@av"];return v}function z(a,e,g){var l=a.root;a={};if(l.TextVars||l.Graphics)a[0]=a[""]=n(l,e,g);if(l.Groups){var f=0,v=l.Groups.Group,d;x.isArray(v)||
(v=[v]);for(d=v.length;f<d;f++){var b=n(v[f],e,g);a[b.$id]=b}}e=l.GroupIds?l.GroupIds.split(","):[];return{ids:e,items:a,total:e.length}}var B=a.AdMessage||(a.AdMessage={}),x=a.lib;B.build=function(a){function v(){var c=K?K.length:0;return{total:c,totalPages:Math.ceil(c/d),pageSize:d,ids:K||[],limit:p}}function n(c,a,b){B.load(T[c]+"&"+a,function(c,a){c?b(c):b(null,z(a,t,k))})}function l(c){if(c)for(var a in c)c.hasOwnProperty(a)&&(Q[a]=c[a])}var f=u.dhtml&&dhtml.getVar()||{},p=e(a.limit)||100,d=
e(a.pageSize)||1,b=e(a.cid||f.cid),r=e(a.tid||f.tid),C=e(a.tv||f.tv)||+new Date,A=e(a.bn||f.bn),h=a.gid||f.gid||0,k=a.clickTAG||"",t=(a.statics||a.domain||f.staticDomain||f.domain).replace(/\/+$/,""),m=(a.domain||f.domain).replace(/(\w+:\/\/[^\/]+\/).*/,"$1"),T={adMessage:m+"Serving/AdMessage/?",recommendations:m+"dco/recommendations/?",products:m+"dco/products/?"};b="aid="+b+"&tid="+r+"&tv="+C;r=e(a.icid||f.icid)||"0";C=f.unloadID||"0";m=f.geo||"0;0;0";var R=a.eshopId||f.trackingSetupId||"0",S=f.ADFbanID||
"0",y=e(a.rotseqno||f.rotseqno),M=a.smid||f.smid,D=a.dcoEngineId||f.dcoEngineId;f.versionListId&&(b+="&versionListId="+f.versionListId);f.versionId&&(b+="&versionId="+f.versionId);r&&(b+="&icid="+r);R&&(b+="&eid="+R);y&&(b+="&rotseqno="+y);M&&(b+="&smid="+M);D&&(b+="&dco="+D);S&&(b+="&bnrid="+S);C&&(b+="&intid="+C);m&&(b+="&geo="+m.split(";").join(","));for(var U in T)T[U]+=b;var Q={},K,G=0,I=w(100,function(c,a){c*=d;var b=c+2*d;G=Math.max(G,b);if(K)if(c=K.slice(c,b),c.length)a(null,c,v());else try{throw Error("AdMessage page not found.");
}catch(L){a(L)}},function(c){n(D?"recommendations":"adMessage","bn="+A+"&gcnt="+p+"&pgsz="+Math.min(G,p),function(a,b){if(a)c(a);else if(l(b.items),(K=b.ids)&&K.length)c();else try{throw Error("AdMessage template doesn't contain groups.");}catch(L){c(L)}});G=0}),J={},c=[],Y=w(100,function(a,b){for(var h=a._test||0,k=[],d=0,t=a.length,r,m;d<t;d++)(m=Q[r=a[d]])?k.push(m):J[r]||(J[r]=!0,c.push(r));a._test=++h;if(k.length==a.length)b(null,k,v());else if(4<h)try{throw Error("AdMessage group"+((1<a.length?
's "':' "')+a.join(", "))+'" not found.');}catch(q){b(q)}},function(a){c.length?n(D?"products":"adMessage","bn="+A+"&gid="+c.join(","),function(c,b){J={};c?a(c):(l(b.items),a())}):setTimeout(function(){a()},100);c=[]});f.dynamicAdContent&&l(z(f.dynamicAdContent,t,k).items);return{setProperties:function(c){var a=c.pageSize>>0||d;c=c.limit>>0||p;0<c&&(p=c);0<a&&(d=Math.min(a,p))},getProperties:v,getPage:function(c,a){I((c>>0)-1,function(c,b){c?a(c):(Y(b.slice(0,d),a),Y(b.slice(d),g))})},getItems:function(c,
a){Y(x.isArray(c)?c:[c],a)},getDefault:function(c){Y([h],function(a,b,h){c(a,b&&b[0],h)})}}};B.load=function(a,e){var g=x.gid("adform_com_"),l=p.createElement("script"),f=function(){d();try{throw Error("AdMessage load error.");}catch(b){e(b)}},w=function(a){d();e(null,a)},d=function(){l.parentNode.removeChild(l);u[g]=l.onerror=l.onload=f=w=d=l=null};l.type="text/javascript";l.src=a+"&format=json&callback="+encodeURIComponent(g);l.onload=l.onerror=function(){setTimeout(f,1E3)};u[g]=w;a=x.byTag(p,"script")[0];
a.parentNode.insertBefore(l,a)}})(Adform=window.Adform||{},window,document);
(function(a,u,p,e){function g(){}function w(a){for(var b=f.length;0<b--;)if(f[b][0]==a)return f[b][1]}function n(a,e,g){function h(c){if(c&&R)b(R,"touchstart",H);else if(!R)try{(R=a.defaultView.frameElement)&&d(R,"touchstart",H)}catch(Y){}}var k=w(a),t,m;k?t=k._:f.push([a,k={_:t=new l,_destroy:function(){t.clear();delete this._;delete this._destroy;for(var c in this)if("function"==typeof this[c])this[c]();for(c=f.length;0<c--;)if(f[c][0]==a){f.splice(c,1);break}}}]);var r,R,C,y,p,n,A,v;P.isIOS&&a.defaultView.frameElement&&
{click:1,mousedown:1,mouseup:1}[e]&&d(g,e,H);if(!k[e])switch(e){case "swipe":var u=function(a){if(r=x(t,a.target,"swipe")[0])a.preventDefault(),(a=a&&a.targetTouches)&&(a=a[0])&&(C=a.pageX,p=a.pageY,A=(new Date).getTime())};var G=function(a){var b=a&&a.targetTouches;r&&(a.preventDefault(),b&&(b=b[0])&&A&&(y=b.pageX,n=b.pageY,v=(new Date).getTime(),.2<Math.sqrt(Math.pow(y-C,2)+Math.pow(n-p,2))/(v-A)&&(a=p-n,b={type:"swipe"},b.directionX=0<C-y?"left":"right",b.directionY=0<a?"up":"down",b.target=r[1],
A=0,B(t,r[1],b))))};d(a,"touchstart",u);d(a,"touchend",G);d(a,"touchmove",G);h();k[e]=function(){b(a,"touchstart",u);b(a,"touchend",G);b(a,"touchmove",G);h(!0)};break;case "hover":if(a.addEventListener){var I=function(a){a=a.target;m!=a&&z(t,m,m=a)};var J=function(a){a=a.relatedTarget;m!=a&&z(t,m,m=a)}}else I=function(b){b=(a.defaultView||a.parentWindow).event.srcElement;m!=b&&z(t,m,m=b)},J=function(b){b=(a.defaultView||a.parentWindow).event.toElement;m!=b&&z(t,m,m=b)};d(a,"mouseover",I);d(a,"mouseout",
J);d(a,"mousemove",I);k[e]=function(){b(a,"mouseover",I);b(a,"mouseout",J);b(a,"mousemove",I);m=null};break;case "click":case "mousedown":case "mouseup":case "touchstart":case "touchmove":case "touchend":I=a.addEventListener?function(a){B(t,a.target,a)}:function(b){b=(a.defaultView||a.parentWindow).event;B(t,b.srcElement,b)},d(a,e,I),k[e]=function(){b(a,e,I)}}return!!k[e]}function z(a,b,d){d=x(a,d,"hover");b=x(a,b,"hover");for(var h=d.length,k=h,e=b.length,m=e-h;0<k--&&d[k][1]==(b[m+k]&&b[m+k][1]););
d.length=h=k+1;b.length=e=m+k+1;var g,f=a._events;if(f){for(m=k=-1;++m<e;)f[g=b[m][0]]&&a.emit(g,b[m][1],"hoverout");for(;++k<h;)f[g=d[k][0]]&&a.emit(g,d[k][1],"hoverin")}}function B(a,b,d,h){h=h||d;b=x(a,b,d.type);d=b.length;for(var k=0,e;e=b[k],k++<d;)a.emit(e[0],e[1],h)}function x(a,b,d){a=a._events;var h,k,e,m=[];if(a)for(;b&&"undefined"!=(e=typeof(k=b.className));)"string"==e&&~k.indexOf("adform-dom-")&&a[h=v(b)+":"+d]&&(m[m.length]=[h,b]),b=b.parentNode;return m}function v(a){a=a.className;
return~a.indexOf("adform-dom-")?a.match(N)[1]:P.gid()}function H(){}a.RMB=a.RMB||{};a=a.RMB;a.DOMEvents=g;var P=a.lib,l=a.EventEmitter,f=[],N=/adform-dom-(\S+)/,d=P.addEvent,b=P.removeEvent;g.has=function(a){return!!{hover:1,mousedown:1,mouseup:1,click:1,swipe:1,touchstart:1,touchmove:1,touchend:1}[a]};g.on=function(a,b,d){var h=a.ownerDocument;if(n(h,b,a)){var k=v(a);P.addClass(a,"adform-dom-"+k);w(h)._.on(k+":"+b,d);return!0}return!1};g.off=function(a,b,d){w(a.ownerDocument)._.off(v(a)+":"+b,d)};
g.destroy=function(a){w(a)._destroy()}})(Adform=window.Adform||{},window,document);
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(a){function u(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return C[a]||a})}function p(a,b,d,e){e=e||"<template>";var h=b.split("\n"),k=Math.max(d-3,0);h=h.slice(k,Math.min(h.length,d+3));for(var g,m=0,f=h.length;m<f;++m)g=m+k+1,h[m]=(g===d?" >> ":"    ")+h[m];a.template=b;a.line=d;a.file=e;a.message=[e+":"+d,h.join("\n"),"",a.message].join("\n");return a}function e(a,b,d){if("."===a)return b[b.length-1];a=a.split(".");for(var h=a.length-1,e=a[h],k,g,f=b.length,t,l;f;){l=
b.slice(0);g=b[--f];for(t=0;t<h;){g=g[a[t++]];if(null==g)break;l.push(g)}if(g&&"object"===typeof g&&e in g){k=g[e];break}}"function"===typeof k&&(k=k.call(l[l.length-1]));return null==k?d:k}function g(a,b,d,g){var h="";a=e(a,b);if(g){if(null==a||!1===a||l(a)&&0===a.length)h+=d()}else if(l(a))f(a,function(a){b.push(a);h+=d();b.pop()});else if("object"===typeof a)b.push(a),h+=d(),b.pop();else if("function"===typeof a){var k=b[b.length-1];h+=a.call(k,d(),function(a){return B(a,k)})||""}else a&&(h+=d());
return h}function w(b,e){e=e||{};for(var h=e.tags||a.tags,g=h[0],k=h[h.length-1],f=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],l=[],w=!1,n=!1,v=function(){if(!w||n||e.space)l=[];else for(;l.length;)f.splice(l.pop(),1);n=w=!1},r=[],u,z,x,B=function(a){h=d(a).split(/\s+/);z=h[0];x=h[h.length-1]},A=function(a){f.push('";',u,'\nvar partial = partials["'+d(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},c=function(a,
c){a=d(a);if(""===a)throw p(Error("Section name may not be empty"),b,L,e.file);r.push({name:a,inverted:c});f.push('";',u,'\nvar name = "'+a+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},C=function(a){c(a,!0)},H=function(a){a=d(a);var q=0!=r.length&&r[r.length-1].name;if(!q||a!=q)throw p(Error('Section named "'+a+'" was never opened'),b,L,e.file);a=r.pop();f.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?f.push("\nbuffer += renderSection(name,stack,callback,true);"):
f.push("\nbuffer += renderSection(name,stack,callback);");f.push('\nbuffer += "')},P=function(a){f.push('";',u,'\nbuffer += lookup("'+d(a)+'",stack,"");','\nbuffer += "')},W=function(a){f.push('";',u,'\nbuffer += escapeHTML(lookup("'+d(a)+'",stack,""));','\nbuffer += "')},L=1,O,E,F=0,Z=b.length;F<Z;++F)if(b.slice(F,F+g.length)===g){F+=g.length;O=b.substr(F,1);u="\nline = "+L+";";z=g;x=k;w=!0;switch(O){case "!":F++;E=null;break;case "=":F++;k="="+k;E=B;break;case ">":F++;E=A;break;case "#":F++;E=c;
break;case "^":F++;E=C;break;case "/":F++;E=H;break;case "{":k="}"+k;case "&":F++;n=!0;E=P;break;default:n=!0,E=W}O=b.indexOf(k,F);if(-1===O)throw p(Error('Tag "'+g+'" was not closed properly'),b,L,e.file);g=b.substring(F,O);E&&E(g);for(E=0;~(E=g.indexOf("\n",E));)L++,E++;F=O+k.length-1;g=z;k=x}else switch(O=b.substr(F,1),O){case '"':case "\\":n=!0;f.push("\\"+O);break;case "\r":break;case "\n":l.push(f.length);f.push("\\n");v();L++;break;default:N.test(O)?l.push(f.length):n=!0,f.push(O)}if(0!=r.length)throw p(Error('Section "'+
r[r.length-1].name+'" was not closed properly'),b,L,e.file);v();f.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");k=f.join("").replace(/buffer \+= "";\n/g,"");e.debug&&("undefined"!=typeof console&&console.log?console.log(k):"function"===typeof print&&print(k));return k}function n(a,b){var d=w(a,b),h=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",d);return function(d,k){k=k||{};var f=[d];try{return h(d,k,f,e,u,g,B)}catch(y){throw p(y.error,
a,y.line,b.file);}}}function z(a,b){b=b||{};return!1!==b.cache?(A[a]||(A[a]=n(a,b)),A[a]):n(a,b)}function B(a,b,d){return z(a)(b,d)}a.name="mustache.js";a.version="0.5.0-dev";a.tags=["{{","}}"];a.parse=w;a.compile=z;a.render=B;a.clearCache=function(){A={}};a.to_html=function(a,b,d,e){a=B(a,b,d);if("function"===typeof e)e(a);else return a};var x=Object.prototype.toString,v=Array.isArray,H=Array.prototype.forEach,P=String.prototype.trim;var l=v?v:function(a){return"[object Array]"===x.call(a)};var f=
H?function(a,b,d){return H.call(a,b,d)}:function(a,b,d){for(var e=0,g=a.length;e<g;++e)b.call(d,a[e],e,a)};var N=/^\s*$/;if(P)var d=function(a){return null==a?"":P.call(a)};else{if(N.test("\u00a0")){var b=/^\s+/;var r=/\s+$/}else b=/^[\s\xA0]+/,r=/[\s\xA0]+$/;d=function(a){return null==a?"":String(a).replace(b,"").replace(r,"")}}var C={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},A={}})(Mustache);
(function(a,u,p){function e(){if(u.Ready)for(var c=0;c<Ready.length;c++)n(Ready[c]);u.Ready={push:n}}function g(c,a){var b=t,h="undefined"==typeof t[c],d="undefined"==typeof k[c];if(c)if(h&&d){b=a;try{var r=_Adform.Log.pushMessage;/^c.*tag/i.test(c)?r("flashvars_clicktag",[c,"bn:",t.bn].join(" "),1):"bn"==c?r("flashvars_bn","bn: "+t.bn,1):~"autoPlay loopVideo soundOn inview autoPause playOnExpand".indexOf(c)?r("flashvars_video",[c,"bn:",t.bn].join(" "),0,"info"):~"dcoEngineId dynamicAdContent gid tv tid autoScroll".indexOf(c)?
r("flashvars_dco",[c,"bn:",t.bn].join(" "),0,"info"):r("flashvars_other",[c,"bn:",t.bn].join(" "),0,"info")}catch(O){}}else b=h?k[c]:t[c];return b}function w(c){c=parseInt(c,10);var a=g("videoSources");if(a)for(var b=a.length,h,k=0;k<b;k++)if(h=a[k],h.id==c)return h.file}function n(c){c.call(u);J||(clearTimeout(I),I=setTimeout(function(){J=!0;p.close()},1E3))}function z(c,a){"function"==typeof a&&(c=a);try{throw Error("AdMessage template id is missing");}catch(aa){if("function"==typeof c)c(aa);else throw aa;
}}function B(c,a,b,d){var r=u._Adform&&_Adform.Events;if(r&&r.sendEvent){if(c in y)a=y[c];else if(isNaN(c=parseInt(c,10))||1>c||20<c&&200>c||250<c)throw Error("Custom event id="+c+" must be between 1-20 for engaging and 200-250 for non-engaging events");if(!a)throw Error("Event name is missing");var t=[""];if(b)for(var m in b){var e=m.slice(0,2),g=parseInt(m.slice(2),10);"bv"==e&&0<g&&256>g&&t.push(m+"="+encodeURIComponent(b[m]))}d&&t.push(d);r.sendEvent(k.xId,c,h.assetId,a,t.join("&"),"Standard HTML");
return!0}return!1}function x(c,a){l[c]||(l[c]=Mustache.compile(v(c).text));if(a){if(N.length!=r){for(var b=0;b<N.length;b++)"text/mustache"==N[b].type&&x(N[b].id);r=N.length}return l[c](a,l)}return l[c]}function v(a){return p.getElementById(a)}for(var H=a.RMB.lib,P=H.isArray,l={},f,N=p.getElementsByTagName("script"),d=0,b;d<N.length;d++)if(b=(N[d].src||"").match(/(^.*)rmb\/Adform\.DHTML\.js/)){f=b[1]+"components/";break}var r=0,C=a.RMB.EventEmitter;b=a.RMB.DOMEvents;var A=u._AdformContent||{},h=A.data||
{},k=A.options||{},t=h.flashvars,m=a.tagData;if(!t&&(t={},m)){d=m.customVariables;m=m.clickUrls;if(d)for(var T in d)t[T]=d[T];for(var R in m)t[R]=m[R]}var S=new C;a.on=function(){S.on.apply(S,arguments)};a.off=function(){S.off.apply(S,arguments)};a.emit=function(){S.emit.apply(S,arguments)};var y={151:"Previous Product Button Press",150:"Next Product Button Press",143:"Banner Collapse",22:"Other Expands",21:"First Expand",168:"Auto Expands",161:"Hide Expanding Banner Button Press",23:"Close Button Press",
25:"Video Play Start",26:"Played 25% Of Video",27:"Played 50% Of Video",28:"Played 75% Of Video",29:"Video Playback Complete",30:"Play Button Press",31:"Pause Button Press",32:"Stop Button Press",33:"Sound On Button Press",34:"Sound Off Button Press",35:"Full Screen On Button Press",36:"Full Screen Off Button Press",38:"Rewind Button Press","":""};a.EVENT_FIRST_EXPAND=[21,y[21]];a.EVENT_OTHER_EXPAND=[22,y[22]];a.EVENT_CLOSE=[23,y[23]];a.EVENT_COLLAPSE=[143,y[143]];for(d=1;251>d;d++)if(21>d||199<d)a["EVENT_CUSTOM_"+
d]=[d,"Custom Event "+d];a.sendRequest=function(a){(new Image).src=a};a.sendEvent=function(a){var c,b,h=arguments;if(c=P(a)&&1<a.length){for(c=1;c<h.length&&256>c;c++)(b=b||{})["bv"+c]=h[c];c=B(a[0],a[1],b)}return c};a.getClickURL=function(a,b){return g(a||h.defaultClickTAG||"clickTAG",b)||null};a.getLocation=function(){var a=u._Adform&&_Adform.locationInfo||null;a&&(a.lng=a.Longitude,a.lat=a.Latitude);return a};a.getAsset=function(a){return w(a)||null};a.getVar=function(a){return a&&void 0!==t[a]?
t[a]:null};var M=u.dhtml={PREVIOUS_BUTTON_PRESS:151,NEXT_BUTTON_PRESS:150,CLOSE_BUTTON_PRESS:23,COLLAPSE_EVENT:143,EXPAND_EVENT:22,FIRST_EXPAND_EVENT:21,AUTO_EXPAND_EVENT:168,SUPER_CLOSE_EVENT:161,VIDEO_PROG_0:25,VIDEO_PROG_25:26,VIDEO_PROG_50:27,VIDEO_PROG_75:28,VIDEO_PROG_100:29,PLAY_BUTTON_PRESS:30,PAUSE_BUTTON_PRESS:31,STOP_BUTTON_PRESS:32,SOUND_ON_BUTTON_PRESS:33,SOUND_OFF_BUTTON_PRESS:34,FULL_SCREEN_ON_BUTTON_PRESS:35,FULL_SCREEN_OFF_BUTTON_PRESS:36,REWIND_BUTTON_PRESS:38,byId:v,hasClass:H.hasClass,
addClass:H.addClass,removeClass:H.removeClass,mustache:x,sendEvent:function(a,b,h){if(!(D&&D.callDHTMLEvent&&D.callDHTMLEvent.call(D,a)))return a in y&&(h=null),B(a,b,h)},$sendEvent:B,appendEvents:function(a){for(var c in a)y.hasOwnProperty(c)||(y[c]=a[c]);return y},getVar:g,getAsset:w,width:h.width,height:h.height,collapsedWidth:k.colWidth,collapsedHeight:k.colHeight,external:A.external||{},inscreen:new C,sharedEvents:A.sharedEvents||new C,scriptsBase:k.scriptsBase||f+"../",getState:function(){return A.state?
A.state():"visible"},on:b.on,off:b.off,connect:function(a){var c=u._Adform&&_Adform.ADFUtilInstance;a=a||t.bn||"x";c=c?c.getRotSeed():{};c.localConnections||(c.localConnections={});var b=c.localConnections[a];if(!b){b=new C;var h=[];b.expect=function(a,c){if(h.length>=a)c();else b.once("expect:"+a,c);return b};b.join=function(a){h.push(a);b.emit("member",a);b.emit("expect:"+h.length);return b};b.members=h;c.localConnections[a]=b}return b}};try{var D=parent.parent.getVPAIDAd&&parent.parent.getVPAIDAd()}catch(c){}if(D&&
D.callDHTMLEvent){M.vpaid=D;var U=M.external.close;M.external.close=function(){D.callDHTMLEvent.call(D,23);return U.apply(this,arguments)}}M.sharedEvents.on("newListener",function(a){"pageLoadComplete"==a&&setTimeout(function(){M.external.initPoliteMode()},0)});M.adMessage=t.tid?a.AdMessage.build({limit:100,pageSize:5}):{setProperties:z,getProperties:z,getPage:z,getItems:z,getDefault:z};var Q=M.inscreen;M.external.initInScreen&&(M.sharedEvents.on("updateInScreen",function(a){for(var c in a)Q.emit(c,
Q[c]=a[c]);Q.emit("change")}),a.on("newListener",function(c){"visibilityData"===c&&(a.off("newListener",arguments.callee),Q.on("change",function(){a.emit("visibilityData",{isVisible:Q.visible,visibleArea:Q.percent})}))}),Q.once("newListener",function(){setTimeout(function(){M.external.initInScreen()},0)}));components=u.preloadQueue||u.components||[];var K=components.length;for(d=0;d<components.length;d++)p.write('<script src="'+(f+"Adform."+components[d]+".js?bv="+(t.bv||Math.random()))+'">\x3c/script>');
try{var G=p.defaultView.frameElement;G&&H.addEvent(G,"touchstart",function(){})}catch(c){}M.registerComponent=function(a){for(var c=0;c<components.length;c++)components[c]==a&&K--;K||e()};K||e();var I,J})(Adform=window.Adform,window,document);
